CREATE TABLE IF NOT EXISTS kwitansi (
  id TEXT PRIMARY KEY,
  no_kwitansi TEXT NOT NULL,
  tanggal TEXT,
  nama_jamaah TEXT NOT NULL,
  no_wa TEXT,
  paket TEXT,
  program TEXT,
  kamar TEXT,
  theme TEXT,
  header_brand TEXT,
  header_sub TEXT,
  header_ppiu TEXT,
  header_pihk TEXT,
  header_alamat TEXT,
  header_kontak TEXT,
  header_ig TEXT,
  header_tg TEXT,
  logo_data_url TEXT,
  ttd_kasir_nama TEXT,
  ttd_kasir_data_url TEXT,
  stempel_data_url TEXT,
  pax_dewasa INTEGER,
  harga_dewasa REAL,
  pax_bayi INTEGER,
  harga_bayi REAL,
  biaya_tambahan REAL,
  total_harga REAL,
  nominal_bayar REAL,
  kekurangan REAL,
  jenis_bayar TEXT,
  metode TEXT,
  catatan TEXT,
  status TEXT,
  checkboxes TEXT,
  custom_fas TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
